stages:
  - build
  - test
  - deploy


build docs:
  stage: build
  script:
    - tox -e docs
  tags:
    - shared-linux
  artifacts:
    paths:
    - doc/
    expire_in: 1 week


test Linux:
  stage: test
  script:
      - tox
  tags:
    - shared-linux
  coverage: '/^TOTAL.*\s+(\d+\%)$/'


test macOS:
  stage: test
  script:
      - tox
  tags:
    - shared-mac


test Windows:
  stage: test
  script:
      - tox
  tags:
    - shared-win


deploy pip to PyPI:

  stage: deploy
  when: manual
  only:
    - tags

  environment:
    name: PyPI
    url: https://pypi.python.org/pypi/sckit-surgerynditracker

  tags:
    - pip-production

  artifacts:
    paths:
    - dist/

  script:
    # Install packages required to build/publish
    # remove any previous distribution files
    - pip install wheel twine setuptools
    - rm -rf dist

    # bundle installer
    - python setup.py bdist_wheel

    # Upload to pypi
    - twine upload --repository pypi dist/* --username $PYPI_USER --password $PYPI_PASS
