language: python

matrix:
 include:
  - os: linux
    python: 3.6
  - os: linux
    python: 3.7
  - os: linux
    python: 3.8

stages:
 - install
 - test
 - deploy

install:
 - pip install -r requirements-dev.txt

script:
 - coverage erase
 - coverage run -a --source ./sksurgerynditracker -m pytest -v -s ./tests/
 - coverage report -m
 - pylint --rcfile=tests/pylintrc sksurgerynditracker tests

after_success:
 - coveralls

deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASS
  skip_existing: true
  on:
   tags: true
   branch: master
